sudo : required
services:
    - docker

before_install:
    - docker build -t anoopviswappan/react-multi-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true anoopviswappan/react-multi-test npm run test -- --coverage

after_success:
    - docker build -t anoopviswappan/react-multi-client ./client
    - docker build -t anoopviswappan/react-multi-nginx ./nginx
    - docker build -t anoopviswappan/react-multi-server ./server
    - docker build -t anoopviswappan/react-multi-worker ./worker
    #Log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push anoopviswappan/react-multi-client
    - docker push anoopviswappan/react-multi-nginx
    - docker push anoopviswappan/react-multi-server
    - docker push anoopviswappan/react-multi-worker